# Generated by Django 5.2.7 on 2025-10-25 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_course_image_remove_course_profession_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='CourseInfo',
        ),
        migrations.CreateModel(
            name='CourseCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses/images/')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='main.profession')),
            ],
        ),
    ]
