# Generated by Django 5.2.7 on 2025-10-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_course_courseinfo_coursecard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='default.png', upload_to='profile_photos/'),
        ),
    ]
