# Generated by Django 5.2.7 on 2025-10-26 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecard',
            name='info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.courseinfo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='media/profile_photos/'),
        ),
    ]
