# Generated by Django 5.2.7 on 2025-11-01 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_lessontest_question_answer_testresult'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testresult',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='lessontest',
            name='title',
        ),
    ]
