# Generated by Django 5.2.7 on 2025-11-12 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_profile_first_name_profile_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
