# Generated by Django 5.2.7 on 2026-02-23 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_profile_role_aianalysis_classroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aianalysis',
            name='model_name',
        ),
        migrations.AlterField(
            model_name='aianalysis',
            name='recommendations',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aianalysis',
            name='strengths',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aianalysis',
            name='weaknesses',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Classroom',
        ),
    ]
